---
title: Org-mode to Markdown Made Easy
keywords: pandoc, org-mode, markdown, haskell software, converter, stack
description: pandoc powerful document coverter will covert org-mode to markdown format without hassle.
author: Myoungjin Jeon
---

#+STARTUP: inlineimages

** I Kept writing in org-mode and..

 Not to forget how to write down in org-mode or literate haskell, I'm keeping my blog in /.lhs/
 or /.org/ and I realized that when I need to post in [[https://dev.to][/dev.to/]]. I found myself being a
 coverter. It is not very hard but annoying process. And I tried /pandoc/ as a commandline tool.

** Install pandoc
 you can install via =pacman= on arch linux!

 #+begin_src sh
   sh> sudo pacman -S pandoc                       2517ms  Mon 18 Apr 2022 21:54:37
   resolving dependencies...
   looking for conflicting packages...

   Packages (129) haskell-aeson-1.5.6.0-84  haskell-aeson-pretty-0.8.9-35
                  haskell-ansi-terminal-0.11-218  haskell-appar-0.1.8-13
                  haskell-asn1-encoding-0.9.6-154  haskell-asn1-parse-0.9.5-154
                  haskell-asn1-types-0.3.4-133  haskell-assoc-1.0.2-124
                  haskell-async-2.2.4-14  haskell-attoparsec-0.14.4-3

          .. snip ..

                  haskell-x509-store-1.6.9-5  haskell-x509-system-1.6.7-8
                  haskell-x509-validation-1.6.12-10  haskell-xml-1.3.14-30
                  haskell-xml-conduit-1.9.1.1-85  haskell-xml-types-0.3.8-8
                  haskell-zip-archive-0.4.1-161  haskell-zlib-0.6.2.3-62
                  pandoc-2.14.2-42

   Total Download Size:    44.20 MiB
   Total Installed Size:  297.95 MiB

   :: Proceed with installation? [Y/n] n 
 #+end_src

 Oh... Kay... abort mission. because I'm using /stack/ and /stack/ already has installed
 many haskell libraries already.

#+begin_src sh
  sh> stack install pandoc
  .. compiling ....
#+end_src

 TBH, if you are compiling for the first time, it would take a lot of time.
 +/ghc/ is not blazing fast software+. It is up to you, but if you don't use other haskell
 software, I recommends you try to install it via your package system first.

** Pandoc -t markdown

#+begin_src sh
  sh> pandoc -to markdown some-article.org > out.markdown
#+end_src

 and that's it.
 
** Fix metadata

 However, you might need to fix your metadata if you are input in your article.

 It looks like below:

 #+begin_export ascii
--- title: Builtin Benchmark with Go description: writing the benchmark
code in go langauge. keywords: go, golang, benchmark, org-mode, hakyll
author: Myoungjin Jeon ---
 #+end_export

 You can edit by yourself on your favourite editor or below /awk/ programme can take
 out the metadata part.

 save below as /hakyll-pandoc-preproc.awk/

#+begin_src awk
  #!/usr/bin/awk -f

  BEGIN {
      numof_printed = -1;
  }

  {
      if ( $0 ~ /^--*$/ ) {
          numof_printed++;
          if ( numof_printed > 0 ) {
              print $0;
              exit;
          }
      }

      if ( numof_printed >= 0 ) {
          print $0;
          numof_printed++;
      }
  }
#+end_src

#+begin_src sh
  sh> chmod u+x hakyll-pandoc-preproc.awk
  sh> ./hakyll-pandoc-preproc.awk "your-document.org"
---
title: Builtin Benchmark with Go
description: writing the benchmark code in go langauge.
keywords: go, golang, benchmark, org-mode, hakyll
author: Myoungjin Jeon
---
#+end_src

  Or.. maybe it is better for other script language to handle it.

  (to be continued ...)
